[project]
name = "scrape-food"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "folium>=0.20.0",
    "geocoder>=1.38.1",
    "requests>=2.32.4",
]
